### ISSUE TITLE
Create Windows Build

### ISSUE THREAD

**Issue by akrherz** [conda-forge/mapserver-feedstock#47]
> I will also putz around with a windows config for this as well

Scratch that. Adding the old GNU regex library to Conda Forge is not a yak I want to shave for this. I wonder how realistic it is for MapServer to upgrade away from that given it hasn't been released in 10+ years and is GPL and likely pollutes any Windows builds with GPL restrictions.

_Originally posted by @hobu in https://github.com/conda-forge/mapserver-feedstock/issues/46#issuecomment-2155365349_

**Comment by akrherz** [comment]
Thanks for investigating this @hobu, created this issue for others to stumble into if they are curious :)

**Comment by rouault** [comment]
cf https://github.com/MapServer/MapServer/pull/7073 for experimental support of PCRE2
